# Generated by Django 3.0.5 on 2020-11-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_collection',
            name='gpa',
            field=models.FloatField(max_length=4),
        ),
        migrations.AlterField(
            model_name='students_collection',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
