# Generated by Django 3.0.5 on 2020-11-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201128_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_collection',
            name='year',
            field=models.IntegerField(),
        ),
    ]
