version: "3"
services:
  django-platform:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python ./DjangoApi/manage.py migrate && python ./DjangoApi/manage.py runserver 0.0.0.0:8000"
    image: django-platform:dev-latest

    ports:
      - 8000:8000
networks:
  default:
    external:
      name: dev_net
